module Openlayer
  module Models
    module Workspaces
      type api_key_update_response =
        {
          id: String,
          date_created: Time,
          date_last_used: Time?,
          date_updated: Time,
          secure_key: String,
          status: Openlayer::Models::Workspaces::APIKeyUpdateResponse::status,
          expires_at: Time?,
          last_rotated_at: Time?,
          name: String?,
          previous_key_expires_at: Time?,
          secret: String
        }

      class APIKeyUpdateResponse < Openlayer::Internal::Type::BaseModel
        attr_accessor expires_at: Time?

        attr_accessor name: String?

        attr_accessor id: String

        attr_accessor date_created: Time

        attr_accessor date_last_used: Time?

        attr_accessor date_updated: Time

        attr_accessor secure_key: String

        attr_accessor status: Openlayer::Models::Workspaces::APIKeyUpdateResponse::status

        attr_accessor last_rotated_at: Time?

        attr_accessor previous_key_expires_at: Time?

        attr_reader secret: String?

        def secret=: (String) -> String

        def initialize: (
          id: String,
          date_created: Time,
          date_last_used: Time?,
          date_updated: Time,
          secure_key: String,
          status: Openlayer::Models::Workspaces::APIKeyUpdateResponse::status,
          ?expires_at: Time?,
          ?last_rotated_at: Time?,
          ?name: String?,
          ?previous_key_expires_at: Time?,
          ?secret: String
        ) -> void

        def to_hash: -> {
          id: String,
          date_created: Time,
          date_last_used: Time?,
          date_updated: Time,
          secure_key: String,
          status: Openlayer::Models::Workspaces::APIKeyUpdateResponse::status,
          expires_at: Time?,
          last_rotated_at: Time?,
          name: String?,
          previous_key_expires_at: Time?,
          secret: String
        }

        type status = :active | :rotating | :expired

        module Status
          extend Openlayer::Internal::Type::Enum

          ACTIVE: :active
          ROTATING: :rotating
          EXPIRED: :expired

          def self?.values: -> ::Array[Openlayer::Models::Workspaces::APIKeyUpdateResponse::status]
        end
      end
    end
  end
end
