module Openlayer
  module Models
    module Workspaces
      type api_key_create_params =
        { workspace_id: String, name: String? }
        & Openlayer::Internal::Type::request_parameters

      class APIKeyCreateParams < Openlayer::Internal::Type::BaseModel
        extend Openlayer::Internal::Type::RequestParameters::Converter
        include Openlayer::Internal::Type::RequestParameters

        attr_accessor workspace_id: String

        attr_accessor name: String?

        def initialize: (
          workspace_id: String,
          ?name: String?,
          ?request_options: Openlayer::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          name: String?,
          request_options: Openlayer::RequestOptions
        }
      end
    end
  end
end
