module Openlayer
  module Models
    module Workspaces
      type invite_list_params =
        { page: Integer, per_page: Integer }
        & Openlayer::Internal::Type::request_parameters

      class InviteListParams < Openlayer::Internal::Type::BaseModel
        extend Openlayer::Internal::Type::RequestParameters::Converter
        include Openlayer::Internal::Type::RequestParameters

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader per_page: Integer?

        def per_page=: (Integer) -> Integer

        def initialize: (
          ?page: Integer,
          ?per_page: Integer,
          ?request_options: Openlayer::request_opts
        ) -> void

        def to_hash: -> {
          page: Integer,
          per_page: Integer,
          request_options: Openlayer::RequestOptions
        }
      end
    end
  end
end
