module Openlayer
  module Models
    module Workspaces
      type invite_create_response =
        {
          items: ::Array[Openlayer::Models::Workspaces::InviteCreateResponse::Item]
        }

      class InviteCreateResponse < Openlayer::Internal::Type::BaseModel
        attr_accessor items: ::Array[Openlayer::Models::Workspaces::InviteCreateResponse::Item]

        def initialize: (
          items: ::Array[Openlayer::Models::Workspaces::InviteCreateResponse::Item]
        ) -> void

        def to_hash: -> {
          items: ::Array[Openlayer::Models::Workspaces::InviteCreateResponse::Item]
        }

        type item =
          {
            id: String,
            creator: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Creator,
            date_created: Time,
            email: String,
            role: Openlayer::Models::Workspaces::InviteCreateResponse::Item::role,
            status: Openlayer::Models::Workspaces::InviteCreateResponse::Item::status,
            workspace: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Workspace
          }

        class Item < Openlayer::Internal::Type::BaseModel
          attr_accessor creator: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Creator

          attr_accessor email: String

          attr_accessor role: Openlayer::Models::Workspaces::InviteCreateResponse::Item::role

          attr_accessor status: Openlayer::Models::Workspaces::InviteCreateResponse::Item::status

          attr_accessor id: String

          attr_accessor date_created: Time

          attr_accessor workspace: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Workspace

          def initialize: (
            id: String,
            creator: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Creator,
            date_created: Time,
            email: String,
            role: Openlayer::Models::Workspaces::InviteCreateResponse::Item::role,
            status: Openlayer::Models::Workspaces::InviteCreateResponse::Item::status,
            workspace: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Workspace
          ) -> void

          def to_hash: -> {
            id: String,
            creator: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Creator,
            date_created: Time,
            email: String,
            role: Openlayer::Models::Workspaces::InviteCreateResponse::Item::role,
            status: Openlayer::Models::Workspaces::InviteCreateResponse::Item::status,
            workspace: Openlayer::Models::Workspaces::InviteCreateResponse::Item::Workspace
          }

          type creator = { id: String, name: String?, username: String? }

          class Creator < Openlayer::Internal::Type::BaseModel
            attr_accessor name: String?

            attr_accessor username: String?

            attr_reader id: String?

            def id=: (String) -> String

            def initialize: (
              ?id: String,
              ?name: String?,
              ?username: String?
            ) -> void

            def to_hash: -> { id: String, name: String?, username: String? }
          end

          type role = :ADMIN | :MEMBER | :VIEWER

          module Role
            extend Openlayer::Internal::Type::Enum

            ADMIN: :ADMIN
            MEMBER: :MEMBER
            VIEWER: :VIEWER

            def self?.values: -> ::Array[Openlayer::Models::Workspaces::InviteCreateResponse::Item::role]
          end

          type status = :accepted | :pending

          module Status
            extend Openlayer::Internal::Type::Enum

            ACCEPTED: :accepted
            PENDING: :pending

            def self?.values: -> ::Array[Openlayer::Models::Workspaces::InviteCreateResponse::Item::status]
          end

          type workspace =
            {
              id: String,
              date_created: Time,
              member_count: Integer,
              name: String,
              slug: String
            }

          class Workspace < Openlayer::Internal::Type::BaseModel
            attr_accessor name: String

            attr_accessor slug: String

            attr_accessor id: String

            attr_accessor date_created: Time

            attr_accessor member_count: Integer

            def initialize: (
              id: String,
              date_created: Time,
              member_count: Integer,
              name: String,
              slug: String
            ) -> void

            def to_hash: -> {
              id: String,
              date_created: Time,
              member_count: Integer,
              name: String,
              slug: String
            }
          end
        end
      end
    end
  end
end
