module Openlayer
  class CommitRetrieveParams = Openlayer::Models::CommitRetrieveParams

  module Commits = Openlayer::Models::Commits

  class InferencePipelineDeleteParams = Openlayer::Models::InferencePipelineDeleteParams

  class InferencePipelineRetrieveParams = Openlayer::Models::InferencePipelineRetrieveParams

  module InferencePipelines = Openlayer::Models::InferencePipelines

  class InferencePipelineUpdateParams = Openlayer::Models::InferencePipelineUpdateParams

  class ProjectCreateParams = Openlayer::Models::ProjectCreateParams

  class ProjectDeleteParams = Openlayer::Models::ProjectDeleteParams

  class ProjectListParams = Openlayer::Models::ProjectListParams

  module Projects = Openlayer::Models::Projects

  module Storage = Openlayer::Models::Storage

  class TestEvaluateParams = Openlayer::Models::TestEvaluateParams

  class TestListResultsParams = Openlayer::Models::TestListResultsParams

  class WorkspaceRetrieveParams = Openlayer::Models::WorkspaceRetrieveParams

  module Workspaces = Openlayer::Models::Workspaces

  class WorkspaceUpdateParams = Openlayer::Models::WorkspaceUpdateParams
end
