module Openlayer
  module Models
    module Governance
      module Frameworks
        type document_retrieve_params =
          { framework_id: String, document_id: String }
          & Openlayer::Internal::Type::request_parameters

        class DocumentRetrieveParams < Openlayer::Internal::Type::BaseModel
          extend Openlayer::Internal::Type::RequestParameters::Converter
          include Openlayer::Internal::Type::RequestParameters

          attr_accessor framework_id: String

          attr_accessor document_id: String

          def initialize: (
            framework_id: String,
            document_id: String,
            ?request_options: Openlayer::request_opts
          ) -> void

          def to_hash: -> {
            framework_id: String,
            document_id: String,
            request_options: Openlayer::RequestOptions
          }
        end
      end
    end
  end
end
