module Openlayer
  module Models
    module InferencePipelines
      type row_create_params =
        {
          inference_pipeline_id: String,
          asc: bool,
          page: Integer,
          per_page: Integer,
          sort_column: String,
          column_filters: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::column_filter]?,
          exclude_row_id_list: ::Array[Integer]?,
          not_search_query_and: ::Array[String]?,
          not_search_query_or: ::Array[String]?,
          row_id_list: ::Array[Integer]?,
          search_query_and: ::Array[String]?,
          search_query_or: ::Array[String]?
        }
        & Openlayer::Internal::Type::request_parameters

      class RowCreateParams < Openlayer::Internal::Type::BaseModel
        extend Openlayer::Internal::Type::RequestParameters::Converter
        include Openlayer::Internal::Type::RequestParameters

        attr_accessor inference_pipeline_id: String

        attr_reader asc: bool?

        def asc=: (bool) -> bool

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader per_page: Integer?

        def per_page=: (Integer) -> Integer

        attr_reader sort_column: String?

        def sort_column=: (String) -> String

        attr_accessor column_filters: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::column_filter]?

        attr_accessor exclude_row_id_list: ::Array[Integer]?

        attr_accessor not_search_query_and: ::Array[String]?

        attr_accessor not_search_query_or: ::Array[String]?

        attr_accessor row_id_list: ::Array[Integer]?

        attr_accessor search_query_and: ::Array[String]?

        attr_accessor search_query_or: ::Array[String]?

        def initialize: (
          inference_pipeline_id: String,
          ?asc: bool,
          ?page: Integer,
          ?per_page: Integer,
          ?sort_column: String,
          ?column_filters: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::column_filter]?,
          ?exclude_row_id_list: ::Array[Integer]?,
          ?not_search_query_and: ::Array[String]?,
          ?not_search_query_or: ::Array[String]?,
          ?row_id_list: ::Array[Integer]?,
          ?search_query_and: ::Array[String]?,
          ?search_query_or: ::Array[String]?,
          ?request_options: Openlayer::request_opts
        ) -> void

        def to_hash: -> {
          inference_pipeline_id: String,
          asc: bool,
          page: Integer,
          per_page: Integer,
          sort_column: String,
          column_filters: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::column_filter]?,
          exclude_row_id_list: ::Array[Integer]?,
          not_search_query_and: ::Array[String]?,
          not_search_query_or: ::Array[String]?,
          row_id_list: ::Array[Integer]?,
          search_query_and: ::Array[String]?,
          search_query_or: ::Array[String]?,
          request_options: Openlayer::RequestOptions
        }

        type column_filter =
          Openlayer::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter
          | Openlayer::InferencePipelines::RowCreateParams::ColumnFilter::NumericColumnFilter
          | Openlayer::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter

        module ColumnFilter
          extend Openlayer::Internal::Type::Union

          type set_column_filter =
            {
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::operator,
              value: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::value]
            }

          class SetColumnFilter < Openlayer::Internal::Type::BaseModel
            attr_accessor measurement: String

            attr_accessor operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::operator

            attr_accessor value: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::value]

            def initialize: (
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::operator,
              value: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::value]
            ) -> void

            def to_hash: -> {
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::operator,
              value: ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::value]
            }

            type operator =
              :contains_none
              | :contains_any
              | :contains_all
              | :one_of
              | :none_of

            module Operator
              extend Openlayer::Internal::Type::Enum

              CONTAINS_NONE: :contains_none
              CONTAINS_ANY: :contains_any
              CONTAINS_ALL: :contains_all
              ONE_OF: :one_of
              NONE_OF: :none_of

              def self?.values: -> ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::operator]
            end

            type value = String | Float

            module Value
              extend Openlayer::Internal::Type::Union

              def self?.variants: -> ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::SetColumnFilter::value]
            end
          end

          type numeric_column_filter =
            {
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::NumericColumnFilter::operator,
              value: Float?
            }

          class NumericColumnFilter < Openlayer::Internal::Type::BaseModel
            attr_accessor measurement: String

            attr_accessor operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::NumericColumnFilter::operator

            attr_accessor value: Float?

            def initialize: (
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::NumericColumnFilter::operator,
              value: Float?
            ) -> void

            def to_hash: -> {
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::NumericColumnFilter::operator,
              value: Float?
            }

            type operator = :> | :>= | :is | :< | :<= | :!=

            module Operator
              extend Openlayer::Internal::Type::Enum

              GREATER: :>
              GREATER_OR_EQUALS: :>=
              IS: :is
              LESS: :<
              LESS_OR_EQUALS: :<=
              NOT_EQUALS: :!=

              def self?.values: -> ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::NumericColumnFilter::operator]
            end
          end

          type string_column_filter =
            {
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::operator,
              value: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::value
            }

          class StringColumnFilter < Openlayer::Internal::Type::BaseModel
            attr_accessor measurement: String

            attr_accessor operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::operator

            attr_accessor value: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::value

            def initialize: (
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::operator,
              value: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::value
            ) -> void

            def to_hash: -> {
              measurement: String,
              operator: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::operator,
              value: Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::value
            }

            type operator = :is | :!=

            module Operator
              extend Openlayer::Internal::Type::Enum

              IS: :is
              NOT_EQUALS: :!=

              def self?.values: -> ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::operator]
            end

            type value = String | bool

            module Value
              extend Openlayer::Internal::Type::Union

              def self?.variants: -> ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::ColumnFilter::StringColumnFilter::value]
            end
          end

          def self?.variants: -> ::Array[Openlayer::Models::InferencePipelines::RowCreateParams::column_filter]
        end
      end
    end
  end
end
