# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "openlayer/version"
require_relative "openlayer/internal/util"
require_relative "openlayer/internal/type/converter"
require_relative "openlayer/internal/type/unknown"
require_relative "openlayer/internal/type/boolean"
require_relative "openlayer/internal/type/file_input"
require_relative "openlayer/internal/type/enum"
require_relative "openlayer/internal/type/union"
require_relative "openlayer/internal/type/array_of"
require_relative "openlayer/internal/type/hash_of"
require_relative "openlayer/internal/type/base_model"
require_relative "openlayer/internal/type/base_page"
require_relative "openlayer/internal/type/request_parameters"
require_relative "openlayer/internal"
require_relative "openlayer/request_options"
require_relative "openlayer/file_part"
require_relative "openlayer/errors"
require_relative "openlayer/internal/transport/base_client"
require_relative "openlayer/internal/transport/pooled_net_requester"
require_relative "openlayer/client"
require_relative "openlayer/models/commit_retrieve_params"
require_relative "openlayer/models/commit_retrieve_response"
require_relative "openlayer/models/commits/test_result_list_params"
require_relative "openlayer/models/commits/test_result_list_response"
require_relative "openlayer/models/inference_pipeline_delete_params"
require_relative "openlayer/models/inference_pipeline_retrieve_params"
require_relative "openlayer/models/inference_pipeline_retrieve_response"
require_relative "openlayer/models/inference_pipelines/data_stream_params"
require_relative "openlayer/models/inference_pipelines/data_stream_response"
require_relative "openlayer/models/inference_pipelines/row_update_params"
require_relative "openlayer/models/inference_pipelines/row_update_response"
require_relative "openlayer/models/inference_pipelines/test_result_list_params"
require_relative "openlayer/models/inference_pipelines/test_result_list_response"
require_relative "openlayer/models/inference_pipeline_update_params"
require_relative "openlayer/models/inference_pipeline_update_response"
require_relative "openlayer/models/project_create_params"
require_relative "openlayer/models/project_create_response"
require_relative "openlayer/models/project_list_params"
require_relative "openlayer/models/project_list_response"
require_relative "openlayer/models/projects/commit_create_params"
require_relative "openlayer/models/projects/commit_create_response"
require_relative "openlayer/models/projects/commit_list_params"
require_relative "openlayer/models/projects/commit_list_response"
require_relative "openlayer/models/projects/inference_pipeline_create_params"
require_relative "openlayer/models/projects/inference_pipeline_create_response"
require_relative "openlayer/models/projects/inference_pipeline_list_params"
require_relative "openlayer/models/projects/inference_pipeline_list_response"
require_relative "openlayer/models/projects/test_create_params"
require_relative "openlayer/models/projects/test_create_response"
require_relative "openlayer/models/projects/test_list_params"
require_relative "openlayer/models/projects/test_list_response"
require_relative "openlayer/models/projects/test_update_params"
require_relative "openlayer/models/projects/test_update_response"
require_relative "openlayer/models/storage/presigned_url_create_params"
require_relative "openlayer/models/storage/presigned_url_create_response"
require_relative "openlayer/models/test_evaluate_params"
require_relative "openlayer/models/test_evaluate_response"
require_relative "openlayer/models/workspace_retrieve_params"
require_relative "openlayer/models/workspace_retrieve_response"
require_relative "openlayer/models/workspaces/api_key_create_params"
require_relative "openlayer/models/workspaces/api_key_create_response"
require_relative "openlayer/models/workspaces/invite_create_params"
require_relative "openlayer/models/workspaces/invite_create_response"
require_relative "openlayer/models/workspaces/invite_list_params"
require_relative "openlayer/models/workspaces/invite_list_response"
require_relative "openlayer/models/workspace_update_params"
require_relative "openlayer/models/workspace_update_response"
require_relative "openlayer/models"
require_relative "openlayer/resources/commits"
require_relative "openlayer/resources/commits/test_results"
require_relative "openlayer/resources/inference_pipelines"
require_relative "openlayer/resources/inference_pipelines/data"
require_relative "openlayer/resources/inference_pipelines/rows"
require_relative "openlayer/resources/inference_pipelines/test_results"
require_relative "openlayer/resources/projects"
require_relative "openlayer/resources/projects/commits"
require_relative "openlayer/resources/projects/inference_pipelines"
require_relative "openlayer/resources/projects/tests"
require_relative "openlayer/resources/storage"
require_relative "openlayer/resources/storage/presigned_url"
require_relative "openlayer/resources/tests"
require_relative "openlayer/resources/workspaces"
require_relative "openlayer/resources/workspaces/api_keys"
require_relative "openlayer/resources/workspaces/invites"
