module Openlayer
  module Models
    type background_task_retrieve_params =
      { task_id: String } & Openlayer::Internal::Type::request_parameters

    class BackgroundTaskRetrieveParams < Openlayer::Internal::Type::BaseModel
      extend Openlayer::Internal::Type::RequestParameters::Converter
      include Openlayer::Internal::Type::RequestParameters

      attr_accessor task_id: String

      def initialize: (
        task_id: String,
        ?request_options: Openlayer::request_opts
      ) -> void

      def to_hash: -> {
        task_id: String,
        request_options: Openlayer::RequestOptions
      }
    end
  end
end
