module Openlayer
  module Models
    type commit_retrieve_params =
      { project_version_id: String }
      & Openlayer::Internal::Type::request_parameters

    class CommitRetrieveParams < Openlayer::Internal::Type::BaseModel
      extend Openlayer::Internal::Type::RequestParameters::Converter
      include Openlayer::Internal::Type::RequestParameters

      attr_accessor project_version_id: String

      def initialize: (
        project_version_id: String,
        ?request_options: Openlayer::request_opts
      ) -> void

      def to_hash: -> {
        project_version_id: String,
        request_options: Openlayer::RequestOptions
      }
    end
  end
end
