module Openlayer
  module Models
    type project_update_params =
      {
        project_id: String,
        data_retention_days: Integer?,
        description: String?,
        model_developer: String?,
        model_types: ::Array[String]?,
        name: String,
        purpose: String?
      }
      & Openlayer::Internal::Type::request_parameters

    class ProjectUpdateParams < Openlayer::Internal::Type::BaseModel
      extend Openlayer::Internal::Type::RequestParameters::Converter
      include Openlayer::Internal::Type::RequestParameters

      attr_accessor project_id: String

      attr_accessor data_retention_days: Integer?

      attr_accessor description: String?

      attr_accessor model_developer: String?

      attr_accessor model_types: ::Array[String]?

      attr_reader name: String?

      def name=: (String) -> String

      attr_accessor purpose: String?

      def initialize: (
        project_id: String,
        ?data_retention_days: Integer?,
        ?description: String?,
        ?model_developer: String?,
        ?model_types: ::Array[String]?,
        ?name: String,
        ?purpose: String?,
        ?request_options: Openlayer::request_opts
      ) -> void

      def to_hash: -> {
        project_id: String,
        data_retention_days: Integer?,
        description: String?,
        model_developer: String?,
        model_types: ::Array[String]?,
        name: String,
        purpose: String?,
        request_options: Openlayer::RequestOptions
      }
    end
  end
end
