module Openlayer
  module Models
    type workspace_retrieve_params =
      { workspace_id: String } & Openlayer::Internal::Type::request_parameters

    class WorkspaceRetrieveParams < Openlayer::Internal::Type::BaseModel
      extend Openlayer::Internal::Type::RequestParameters::Converter
      include Openlayer::Internal::Type::RequestParameters

      attr_accessor workspace_id: String

      def initialize: (
        workspace_id: String,
        ?request_options: Openlayer::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        request_options: Openlayer::RequestOptions
      }
    end
  end
end
